Created a delay option for the click event
Xetera/ghost-cursor pull request #25
Opened 2021-03-09 11:36 UTC by Nevgup

Hello

I make this PR following the problem I had here : https://github.com/Xetera/ghost-cursor/issues/24
I have a low level in Typescript, if I haven't done anything correct don't hesitate to let me know because it would allow me to improve.

2021-03-09 14:17 UTC, Nevgup commented
You mean i should do that ?
`interface ClickOptions extends MoveOptions { readonly waitForClick: number, delayOptions: number }`

2021-03-09 14:40 UTC, Xetera commented on src/spoof.ts
> +interface ClickOptions extends MoveOptions { readonly waitForClick: number, readonly delayOptions: number }
It should probably also be called something more descriptive like `moveDelay`

2021-03-10 11:37 UTC, Nevgup commented
Now it's good ?

2021-03-10 13:36 UTC, Niek requested changes
@Nevgup can you please check my pending reviews?

2021-03-10 14:44 UTC, Nevgup commented on src/spoof.ts
> +export function path(start: Vector, end: BoundingBox | Vector, spreadOverride?: number): Vector[] {
I think it's good !

2021-03-11 12:54 UTC, merged